name: hashiru
description: "Production Flutter fitness tracking app inspired by Strava."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.8.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  # Maps & Location
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0

  # Charts
  fl_chart: ^0.70.2

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  xml: ^6.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_svg: ^2.2.4
  flutter_launcher_icons: ^0.14.4

  # Fonts
  google_fonts: ^6.2.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/widgets/
    - assets/app/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app/app_icon.png"